# Generated by Django 4.1.1 on 2024-04-24 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ('-created_at',)},
        ),
    ]
